#pragma once

enum EventType {
	GLFW_WINDOW_SIZE_EVENT,
	GLFW_WINDOW_MAXIMIZE_EVENT,
	GLFW_WINDOW_ICONYFY_EVENT,
	GLFW_WINDOW_FOCUS_EVENT,
	GLFW_WINDOW_DROP_EVENT,
	GLFW_KEY_EVENT,
	GLFW_CHAR_EVENT,
	GLFW_MOUSE_BUTTON_EVENT,
	GLFW_MOUSE_CURSOR_POS_EVENT,
	GLFW_MOUSE_SCROLL_EVENT,
	GLFW_CURSOR_ENTER_EVENT,
	GLFW_JOYSTICK_EVENT
};
